source 'https://rubygems.org'

gem 'capybara'
gem "selenium-webdriver" , '3.142.7'
gem 'cucumber', '8.0.0'
gem 'rspec'
gem 'sinatra'
gem 'rest-client'
gem 'json'
gem 'rake', '~> 13.0.3  '
gem 'byebug', '~> 8.2', '>= 8.2.2'
gem 'parallel', '1.22.1'
gem 'capybara-screenshot'
gem 'multipart-post'
gem 'os'
gem 'mongo'
gem 'parallel_tests', '4.0.0'
gem 'regex'
gem 'multipart_body'
gem 'certified'
gem 'mailinator'
gem 'rubysl-securerandom', '~> 2.0'
gem 'sauce_whisk', '0.0.22'
gem 'spreadsheet'
gem 'sendgrid-ruby'
gem 'unicode_utils'
gem 'report_builder'
gem 'rubyXL'
# gem 'appium_lib'
# gem 'appium_capybara'
